name: Go tests and checking

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    name: Run tests
    permissions:
      contents: read
      pull-requests: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build swapper binaries
        run: make swapper

      - name: Run tests
        run: go test -v ./...

  coverage:
    name: Go test coverage check
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Build swapper binaries
        run: make swapper

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          profile: cover.out
          threshold-total: 75

          ## when token is not specified (value '') this feature is turned off
          ## in this example badge is created and committed only for main branch
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges

  update-report-card:
    name: Update report card
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Request and extract Report Card
        run: |
          curl -s -o /dev/null  -w '%{http_code}' 'https://goreportcard.com/checks' --data-raw 'repo=github.com%2Fguionardo%2Fgo'
          curl -s 'https://goreportcard.com/report/github.com/guionardo/go' | grep "var response = " | awk -F' ' '{for (i=4; i<NF; i++) printf("%s ", $i)}' > report.json

      - name: Generate summary
        run: |
          echo "### Resume! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Grade        $(cat report.json | jq .grade)" >> $GITHUB_STEP_SUMMARY
          echo "Average      $(cat report.json | jq .average)" >> $GITHUB_STEP_SUMMARY
          echo "Last Refresh $(cat report.json | jq .last_refresh)" >> $GITHUB_STEP_SUMMARY
          echo "Did error    $(cat report.json | jq .did_error)" >> $GITHUB_STEP_SUMMARY
